-- pdf_report_templates
--
-- Holds report HTML that used to live only under src/main/resources/reports/.
-- CSS, SVG, fonts and images are NOT stored here — they stay file-based under
-- src/main/resources/templates/<template>/, copied flat next to the rendered
-- HTML at request time, exactly as today.
--
-- A report is looked up by "key", the same string clients already send in the
-- `report` form field (normalized: leading "/" and trailing ".html" stripped).
-- When a key has no row here, ReportTemplateService falls back to the
-- classpath file under reports/ — so a report can be migrated to the database
-- independently of the others, or never migrated at all.
--
-- "variables" is documentation only (same idea as notification-service's own
-- variables column) — a JSON object of {"<thymeleaf variable path>": "<label
-- shown to whoever fills in the data payload>"}, e.g.
-- {"portfolioInfo.studentId":"Student ID"}. Nothing in java-pdf reads this
-- column; it exists purely so a person editing a row's `body` in DataGrip/psql
-- can tell which values the template's `data`/`data_set` needs without
-- reading the raw Thymeleaf markup. Nullable — a row can go without it.

create table pdf_report_templates
(
    id        bigint generated by default as identity primary key,
    key       varchar(255) not null unique,
    body      text         not null,
    variables text,
    created_on timestamp(6) not null default current_timestamp,
    updated_on timestamp(6) not null default current_timestamp
);

-- For a database created before created_on/updated_on existed:
-- alter table pdf_report_templates
--     add column created_on timestamp(6) not null default current_timestamp,
--     add column updated_on timestamp(6) not null default current_timestamp;
