-- pdf_report_templates
--
-- Holds report HTML that used to live only under src/main/resources/reports/.
-- CSS, SVG, fonts and images are NOT stored here — they stay file-based under
-- src/main/resources/templates/<template>/, copied flat next to the rendered
-- HTML at request time, exactly as today.
--
-- A report is looked up by "key", the same string clients already send in the
-- `report` form field (normalized: leading "/" and trailing ".html" stripped).
-- When a key has no row here, ReportTemplateService falls back to the
-- classpath file under reports/ — so a report can be migrated to the database
-- independently of the others, or never migrated at all.

create table pdf_report_templates
(
    id   bigint generated by default as identity primary key,
    key  varchar(255) not null unique,
    body text         not null
);
